In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3])

In [3]:
print(np1)

[1 2 3]


In [4]:
np2 = np.array([[1,2],[11,22]])

In [5]:
print(np2)

[[ 1  2]
 [11 22]]


In [7]:
# dtype parameter
np3 = np.array([10, 20, 30], dtype = float)
print(np3)

[10. 20. 30.]


In [8]:
np4 = np.array([[11,21,31],[41,51,61]])
print(np4)

[[11 21 31]
 [41 51 61]]


In [9]:
print(np4.shape)

(2, 3)


In [10]:
np4.shape = (3,2)

In [11]:
print(np4)

[[11 21]
 [31 41]
 [51 61]]


In [12]:
np4.ndim

2

## Prepopulated arrays 

In [17]:
# create a 2d array of zeroes with default dtype to be float
# use order as 'F' for fortran major and 'C' as c major
np.zeros((2,3), dtype = float, order = 'F')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
list1 = [123, 241, 234]

In [19]:
print(list1)

[123, 241, 234]


In [20]:
np5 = np.asarray(list1)

In [21]:
print(np5)

[123 241 234]


In [22]:
np6 = np.linspace(10, 20, 5, endpoint = False)
print(np6)

[10. 12. 14. 16. 18.]


In [24]:
np7 = np.linspace(10, 20, 5, endpoint = True)
print(np7)
print(np7.ndim)

[10.  12.5 15.  17.5 20. ]
1


## Indexing and Slicing

In [27]:
np8 = np.arange(20)
print(np8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
print(np8[6])
print(np8[10:])
print(np8[10:15])

6
[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14]


In [31]:
s1 = slice(2,15,3)
print(np8[s1])

[ 2  5  8 11 14]


In [32]:
# broadcasting of numpy arrays
np9 = np.array([3.3, 4.4, 1.1])
np10 = np.array([10, 30, 30])
result = np9*np10
print(result)

[ 33. 132.  33.]


In [34]:
#iteration over an array
for element in np.nditer(np9):
    print(element)

3.3
4.4
1.1
